// react-ts-example/src/components/Metrics.tsx
import { useState, useEffect } from 'react';
import { usePolyInfer } from '../hooks/usePolyInfer';
import type { MetricsResponse } from '../types';

export const Metrics = () => {
  const [metrics, setMetrics] = useState<MetricsResponse | null>(null);
  const { loading, error, getMetricsData, resetMetricsData, clearCacheData } = usePolyInfer();

  const fetchMetrics = async () => {
    const result = await getMetricsData();
    if (result.success) {
      setMetrics(result);
    }
  };

  const handleResetMetrics = async () => {
    if (window.confirm('Are you sure you want to reset all metrics?')) {
      await resetMetricsData();
      await fetchMetrics(); // Refresh metrics after reset
    }
  };

  const handleClearCache = async () => {
    if (window.confirm('Are you sure you want to clear the cache?')) {
      await clearCacheData();
    }
  };

  useEffect(() => {
    fetchMetrics();
  }, []);

  return (
    <div className="metrics">
      <h2>📊 Metrics</h2>
      <p>Get current performance metrics for all providers.</p>

      <div className="metrics-actions">
        <button onClick={fetchMetrics} disabled={loading}>
          {loading ? '🔄 Refreshing...' : '🔄 Refresh Metrics'}
        </button>
        <button onClick={handleResetMetrics} disabled={loading} className="secondary">
          🔄 Reset Metrics
        </button>
        <button onClick={handleClearCache} disabled={loading} className="secondary">
          🗑️ Clear Cache
        </button>
      </div>

      {error && (
        <div className="error-message">
          <h3>❌ Error</h3>
          <p>{error}</p>
        </div>
      )}

      {metrics && (
        <div className="metrics-data">
          <h3>📈 Provider Metrics</h3>
          <div className="metrics-grid">
            {Object.entries(metrics.metrics).map(([provider, data]) => (
              <div key={provider} className="metric-card">
                <h4>{provider}</h4>
                <div className="metric-stats">
                  <div className="stat">
                    <span className="stat-label">Success:</span>
                    <span className="stat-value success">{data.success}</span>
                  </div>
                  <div className="stat">
                    <span className="stat-label">Failure:</span>
                    <span className="stat-value failure">{data.failure}</span>
                  </div>
                  <div className="stat">
                    <span className="stat-label">Total:</span>
                    <span className="stat-value">{data.count}</span>
                  </div>
                  <div className="stat">
                    <span className="stat-label">Avg Latency:</span>
                    <span className="stat-value">{data.latency}ms</span>
                  </div>
                  {data.count > 0 && (
                    <div className="stat">
                      <span className="stat-label">Success Rate:</span>
                      <span className="stat-value">
                        {((data.success / data.count) * 100).toFixed(1)}%
                      </span>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
          <p className="timestamp">Last updated: {new Date(metrics.timestamp).toLocaleString()}</p>
        </div>
      )}
    </div>
  );
};

// vue-ts-example/src/components/Metrics.vue
<template>
  <div class="metrics">
    <h2>📊 Metrics</h2>
    <p>Get current performance metrics for all providers.</p>

    <div class="metrics-actions">
      <button @click="fetchMetrics" :disabled="loading">
        {{ loading ? '🔄 Refreshing...' : '🔄 Refresh Metrics' }}
      </button>
      <button @click="handleResetMetrics" :disabled="loading" class="secondary">
        🔄 Reset Metrics
      </button>
      <button @click="handleClearCache" :disabled="loading" class="secondary">
        🗑️ Clear Cache
      </button>
    </div>

    <div v-if="error" class="error-message">
      <h3>❌ Error</h3>
      <p>{{ error }}</p>
    </div>

    <div v-if="metrics" class="metrics-data">
      <h3>📈 Provider Metrics</h3>
      <div class="metrics-grid">
        <div v-for="(data, provider) in metrics.metrics" :key="provider" class="metric-card">
          <h4>{{ provider }}</h4>
          <div class="metric-stats">
            <div class="stat">
              <span class="stat-label">Success:</span>
              <span class="stat-value success">{{ data.success }}</span>
            </div>
            <div class="stat">
              <span class="stat-label">Failure:</span>
              <span class="stat-value failure">{{ data.failure }}</span>
            </div>
            <div class="stat">
              <span class="stat-label">Total:</span>
              <span class="stat-value">{{ data.count }}</span>
            </div>
            <div class="stat">
              <span class="stat-label">Avg Latency:</span>
              <span class="stat-value">{{ data.latency }}ms</span>
            </div>
            <div v-if="data.count > 0" class="stat">
              <span class="stat-label">Success Rate:</span>
              <span class="stat-value">
                {{ ((data.success / data.count) * 100).toFixed(1) }}%
              </span>
            </div>
          </div>
        </div>
      </div>
      <p class="timestamp">Last updated: {{ new Date(metrics.timestamp).toLocaleString() }}</p>
    </div>
  </div>
</template>

<script>
import { usePolyInfer } from '../composables/usePolyInfer.js'

export default {
  name: 'AppMetrics',
  setup() {
    return usePolyInfer()
  },
  data() {
    return {
      metrics: null
    }
  },
  mounted() {
    this.fetchMetrics()
  },
  methods: {
    async fetchMetrics() {
      const result = await this.getMetricsData()
      if (result.success) {
        this.metrics = result
      }
    },
    async handleResetMetrics() {
      if (window.confirm('Are you sure you want to reset all metrics?')) {
        await this.resetMetricsData()
        await this.fetchMetrics() // Refresh metrics after reset
      }
    },
    async handleClearCache() {
      if (window.confirm('Are you sure you want to clear the cache?')) {
        await this.clearCacheData()
      }
    }
  }
}
</script>

<style scoped>
/* Component specific styles can be added here if needed */
</style>
