// react-ts-example/src/components/Metrics.tsx
import { useState, useEffect } from 'react';
import { usePolyInfer } from '../hooks/usePolyInfer';
import type { MetricsResponse } from '../types';

export const Metrics = () => {
  const [metrics, setMetrics] = useState<MetricsResponse | null>(null);
  const { loading, error, getMetricsData, resetMetricsData, clearCacheData } = usePolyInfer();

  const fetchMetrics = async () => {
    const result = await getMetricsData();
    if (result.success) {
      setMetrics(result);
    }
  };

  const handleResetMetrics = async () => {
    if (window.confirm('Are you sure you want to reset all metrics?')) {
      await resetMetricsData();
      await fetchMetrics(); // Refresh metrics after reset
    }
  };

  const handleClearCache = async () => {
    if (window.confirm('Are you sure you want to clear the cache?')) {
      await clearCacheData();
    }
  };

  useEffect(() => {
    fetchMetrics();
  }, []);

  return (
    <div className="metrics">
      <h2>📊 Metrics</h2>
      <p>Get current performance metrics for all providers.</p>

      <div className="metrics-actions">
        <button onClick={fetchMetrics} disabled={loading}>
          {loading ? '🔄 Refreshing...' : '🔄 Refresh Metrics'}
        </button>
        <button onClick={handleResetMetrics} disabled={loading} className="secondary">
          🔄 Reset Metrics
        </button>
        <button onClick={handleClearCache} disabled={loading} className="secondary">
          🗑️ Clear Cache
        </button>
      </div>

      {error && (
        <div className="error-message">
          <h3>❌ Error</h3>
          <p>{error}</p>
        </div>
      )}

      {metrics && (
        <div className="metrics-data">
          <h3>📈 Provider Metrics</h3>
          <div className="metrics-grid">
            {Object.entries(metrics.metrics).map(([provider, data]) => (
              <div key={provider} className="metric-card">
                <h4>{provider}</h4>
                <div className="metric-stats">
                  <div className="stat">
                    <span className="stat-label">Success:</span>
                    <span className="stat-value success">{data.success}</span>
                  </div>
                  <div className="stat">
                    <span className="stat-label">Failure:</span>
                    <span className="stat-value failure">{data.failure}</span>
                  </div>
                  <div className="stat">
                    <span className="stat-label">Total:</span>
                    <span className="stat-value">{data.count}</span>
                  </div>
                  <div className="stat">
                    <span className="stat-label">Avg Latency:</span>
                    <span className="stat-value">{data.latency}ms</span>
                  </div>
                  {data.count > 0 && (
                    <div className="stat">
                      <span className="stat-label">Success Rate:</span>
                      <span className="stat-value">
                        {((data.success / data.count) * 100).toFixed(1)}%
                      </span>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
          <p className="timestamp">Last updated: {new Date(metrics.timestamp).toLocaleString()}</p>
        </div>
      )}
    </div>
  );
};

// angular-ts-example/src/app/components/metrics/metrics.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PolyInferService } from '../../services/polyinfer.service';
import type { MetricsResponse } from '../../types';

@Component({
  selector: 'app-metrics',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './metrics.component.html',
  styleUrl: './metrics.component.css'
})
export class MetricsComponent implements OnInit {
  metrics: MetricsResponse | null = null;

  constructor(private polyInferService: PolyInferService) {}

  get loading(): boolean {
    return this.polyInferService.isLoading;
  }

  get error(): string | null {
    return this.polyInferService.currentError;
  }

  ngOnInit() {
    this.fetchMetrics();
  }

  async fetchMetrics() {
    const result = await this.polyInferService.getMetricsData();
    if (result.success) {
      this.metrics = result;
    }
  }

  async handleResetMetrics() {
    if (window.confirm('Are you sure you want to reset all metrics?')) {
      await this.polyInferService.resetMetricsData();
      await this.fetchMetrics(); // Refresh metrics after reset
    }
  }

  async handleClearCache() {
    if (window.confirm('Are you sure you want to clear the cache?')) {
      await this.polyInferService.clearCacheData();
    }
  }
}

<div class="metrics">
  <h2>📊 Metrics</h2>
  <p>Get current performance metrics for all providers.</p>

  <div class="metrics-actions">
    <button (click)="fetchMetrics()" [disabled]="loading">
      {{ loading ? '🔄 Refreshing...' : '🔄 Refresh Metrics' }}
    </button>
    <button (click)="handleResetMetrics()" [disabled]="loading" class="secondary">
      🔄 Reset Metrics
    </button>
    <button (click)="handleClearCache()" [disabled]="loading" class="secondary">
      🗑️ Clear Cache
    </button>
  </div>

  <div *ngIf="error" class="error-message">
    <h3>❌ Error</h3>
    <p>{{ error }}</p>
  </div>

  <div *ngIf="metrics" class="metrics-data">
    <h3>📈 Provider Metrics</h3>
    <div class="metrics-grid">
      <div *ngFor="let metric of metrics.metrics | keyvalue" class="metric-card">
        <h4>{{ metric.key }}</h4>
        <div class="metric-stats">
          <div class="stat">
            <span class="stat-label">Success:</span>
            <span class="stat-value success">{{ metric.value.success }}</span>
          </div>
          <div class="stat">
            <span class="stat-label">Failure:</span>
            <span class="stat-value failure">{{ metric.value.failure }}</span>
          </div>
          <div class="stat">
            <span class="stat-label">Total:</span>
            <span class="stat-value">{{ metric.value.count }}</span>
          </div>
          <div class="stat">
            <span class="stat-label">Avg Latency:</span>
            <span class="stat-value">{{ metric.value.latency }}ms</span>
          </div>
          <div *ngIf="metric.value.count > 0" class="stat">
            <span class="stat-label">Success Rate:</span>
            <span class="stat-value">
              {{ ((metric.value.success / metric.value.count) * 100) | number:'1.1-1' }}%
            </span>
          </div>
        </div>
      </div>
    </div>
    <p class="timestamp">Last updated: {{ metrics.timestamp | date:'medium' }}</p>
  </div>
</div>
