// react-ts-example/src/App.tsx
import { useState } from 'react';
import './App.css';
import { AIRequest } from './components/AIRequest.tsx';
import { Metrics } from './components/Metrics.tsx';
import { Config } from './components/Config.tsx';
import { Demo } from './components/Demo.tsx';
import { Health } from './components/Health.tsx';

type Tab = 'ai' | 'metrics' | 'config' | 'demo' | 'health';

function App() {
  const [activeTab, setActiveTab] = useState<Tab>('ai');

  const tabs = [
    { id: 'ai' as Tab, label: 'AI Request', component: AIRequest },
    { id: 'metrics' as Tab, label: 'Metrics', component: Metrics },
    { id: 'config' as Tab, label: 'Configuration', component: Config },
    { id: 'demo' as Tab, label: 'Demo', component: Demo },
    { id: 'health' as Tab, label: 'Health', component: Health },
  ];

  const ActiveComponent = tabs.find(tab => tab.id === activeTab)?.component || AIRequest;

  return (
    <div className="app">
      <header className="app-header">
        <h1>🚀 GenAI-PolyInfer React Example</h1>
        <p>Demonstrating all features of the genai-polyinfer package</p>
      </header>

      <nav className="tab-navigation">
        {tabs.map(tab => (
          <button
            key={tab.id}
            className={`tab-button ${activeTab === tab.id ? 'active' : ''}`}
            onClick={() => setActiveTab(tab.id)}
          >
            {tab.label}
          </button>
        ))}
      </nav>

      <main className="tab-content">
        <ActiveComponent />
      </main>

      <footer className="app-footer">
        <p>
          Built with React + TypeScript + Vite |
          Powered by <a href="https://github.com/soumik12345/genai-polyinfer" target="_blank" rel="noopener noreferrer">genai-polyinfer</a>
        </p>
      </footer>
    </div>
  );
}

export default App;

// angular-ts-example/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AiRequestComponent } from './components/ai-request/ai-request.component';
import { MetricsComponent } from './components/metrics/metrics.component';
import { ConfigComponent } from './components/config/config.component';
import { DemoComponent } from './components/demo/demo.component';
import { HealthComponent } from './components/health/health.component';

type Tab = 'ai' | 'metrics' | 'config' | 'demo' | 'health';

interface TabItem {
  id: Tab;
  label: string;
  component: any;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    AiRequestComponent,
    MetricsComponent,
    ConfigComponent,
    DemoComponent,
    HealthComponent
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  activeTab: Tab = 'ai';

  tabs: TabItem[] = [
    { id: 'ai', label: 'AI Request', component: AiRequestComponent },
    { id: 'metrics', label: 'Metrics', component: MetricsComponent },
    { id: 'config', label: 'Configuration', component: ConfigComponent },
    { id: 'demo', label: 'Demo', component: DemoComponent },
    { id: 'health', label: 'Health', component: HealthComponent },
  ];

  get activeComponent() {
    return this.tabs.find(tab => tab.id === this.activeTab)?.component || AiRequestComponent;
  }

  setActiveTab(tab: Tab) {
    this.activeTab = tab;
  }
}

<div class="app">
  <header class="app-header">
    <h1>🚀 GenAI-PolyInfer Angular Example</h1>
    <p>Demonstrating all features of the genai-polyinfer package</p>
  </header>

  <nav class="tab-navigation">
    <button
      *ngFor="let tab of tabs"
      class="tab-button"
      [class.active]="activeTab === tab.id"
      (click)="setActiveTab(tab.id)"
    >
      {{ tab.label }}
    </button>
  </nav>

  <main class="tab-content">
    <ng-container [ngSwitch]="activeTab">
      <app-ai-request *ngSwitchCase="'ai'"></app-ai-request>
      <app-metrics *ngSwitchCase="'metrics'"></app-metrics>
      <app-config *ngSwitchCase="'config'"></app-config>
      <app-demo *ngSwitchCase="'demo'"></app-demo>
      <app-health *ngSwitchCase="'health'"></app-health>
    </ng-container>
  </main>

  <footer class="app-footer">
    <p>
      Built with Angular + TypeScript |
      Powered by <a href="https://github.com/soumik12345/genai-polyinfer" target="_blank" rel="noopener noreferrer">genai-polyinfer</a>
    </p>
  </footer>
</div>
